apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8svc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8svc
  template:
    metadata:
      labels:
        name: k8svc
    spec:
      serviceAccountName: k8svc
      containers:
        - name: k8svc
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - k8svc
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8svc"
