kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8svc
subjects:
- kind: ServiceAccount
  name: k8svc
roleRef:
  kind: Role
  name: k8svc
  apiGroup: rbac.authorization.k8s.io
